const RELEASE_BRANCH_PREFIX = "release"
const BUILD_PREFIX = "rc"
const INITIAL_MAJOR_VERSION = "0"
const INITIAL_MINOR_VERSION = "0"
const INITIAL_PATCH_VERSION = "0"
const INITIAL_BUILD_VERSION = "0"
const MAIN_BRANCH_NAME = "main"

export {
    BUILD_PREFIX,
    RELEASE_BRANCH_PREFIX,
    INITIAL_BUILD_VERSION,
    INITIAL_MINOR_VERSION,
    INITIAL_MAJOR_VERSION,
    INITIAL_PATCH_VERSION,
    MAIN_BRANCH_NAME
};